# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2025 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from ..river_window_management_v1 import RiverSeatV1
from .river_xkb_binding_v1 import RiverXkbBindingV1
from .river_xkb_bindings_seat_v1 import RiverXkbBindingsSeatV1


class RiverXkbBindingsV1(Interface):
    """Xkbcommon bindings global interface

    This global interface should only be advertised to the client if the
    :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
    global is also advertised.
    """

    name = "river_xkb_bindings_v1"
    version = 2

    class error(enum.IntEnum):
        object_already_created = 0


class RiverXkbBindingsV1Proxy(Proxy[RiverXkbBindingsV1]):
    interface = RiverXkbBindingsV1

    @RiverXkbBindingsV1.request()
    def destroy(self) -> None:
        """Destroy the :class:`RiverXkbBindingsV1` object

        This request indicates that the client will no longer use the
        :class:`RiverXkbBindingsV1` object.
        """
        self._marshal(0)
        self._destroy()

    @RiverXkbBindingsV1.request(
        Argument(ArgumentType.Object, interface=RiverSeatV1),
        Argument(ArgumentType.NewId, interface=RiverXkbBindingV1),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def get_xkb_binding(self, seat: RiverSeatV1, keysym: int, modifiers: int) -> Proxy[RiverXkbBindingV1]:
        """Define a new xkbcommon key binding

        Define a key binding for the given seat in terms of an xkbcommon keysym
        and other configurable properties.

        The new key binding is not enabled until initial configuration is
        completed and the enable request is made during a manage sequence.

        :param seat:
        :type seat:
            :class:`~pywayland.protocol.river_window_management_v1.RiverSeatV1`
        :param keysym:
            an xkbcommon keysym
        :type keysym:
            `ArgumentType.Uint`
        :param modifiers:
        :type modifiers:
            `ArgumentType.Uint`
        :returns:
            :class:`~pywayland.protocol.river_xkb_bindings_v1.RiverXkbBindingV1`
        """
        id = self._marshal_constructor(1, RiverXkbBindingV1, seat, keysym, modifiers)
        return id

    @RiverXkbBindingsV1.request(
        Argument(ArgumentType.NewId, interface=RiverXkbBindingsSeatV1),
        Argument(ArgumentType.Object, interface=RiverSeatV1),
        version=2,
    )
    def get_seat(self, seat: RiverSeatV1) -> Proxy[RiverXkbBindingsSeatV1]:
        """Manage seat-specific state

        Create an object to manage seat-specific xkb bindings state.

        It is a protocol error to make this request more than once for a given
        :class:`~pywayland.protocol.river_window_management_v1.RiverSeatV1`
        object.

        :param seat:
        :type seat:
            :class:`~pywayland.protocol.river_window_management_v1.RiverSeatV1`
        :returns:
            :class:`~pywayland.protocol.river_xkb_bindings_v1.RiverXkbBindingsSeatV1`
        """
        id = self._marshal_constructor(2, RiverXkbBindingsSeatV1, seat)
        return id


class RiverXkbBindingsV1Resource(Resource):
    interface = RiverXkbBindingsV1


class RiverXkbBindingsV1Global(Global):
    interface = RiverXkbBindingsV1


RiverXkbBindingsV1._gen_c()
RiverXkbBindingsV1.proxy_class = RiverXkbBindingsV1Proxy
RiverXkbBindingsV1.resource_class = RiverXkbBindingsV1Resource
RiverXkbBindingsV1.global_class = RiverXkbBindingsV1Global
