# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2026 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .river_xkb_keyboard_v1 import RiverXkbKeyboardV1
from .river_xkb_keymap_v1 import RiverXkbKeymapV1


class RiverXkbConfigV1(Interface):
    """Xkb config global interface

    Global interface for configuring xkb devices.

    This global should only be advertised if
    :class:`~pywayland.protocol.river_input_management_v1.RiverInputManagerV1`
    is advertised as well.
    """

    name = "river_xkb_config_v1"
    version = 1

    class error(enum.IntEnum):
        invalid_destroy = 0
        invalid_format = 1

    class keymap_format(enum.IntEnum):
        text_v1 = 1
        text_v2 = 2


class RiverXkbConfigV1Proxy(Proxy[RiverXkbConfigV1]):
    interface = RiverXkbConfigV1

    @RiverXkbConfigV1.request()
    def stop(self) -> None:
        """Stop sending events

        This request indicates that the client no longer wishes to receive
        events on this object.

        The Wayland protocol is asynchronous, which means the server may send
        further events until the stop request is processed. The client must
        wait for a :func:`RiverXkbConfigV1.finished()` event before destroying
        this object.
        """
        self._marshal(0)

    @RiverXkbConfigV1.request()
    def destroy(self) -> None:
        """Destroy the :class:`RiverXkbConfigV1` object

        This request should be called after the finished event has been
        received to complete destruction of the object.

        It is a protocol error to make this request before the finished event
        has been received.

        If a client wishes to destroy this object it should send a
        :func:`RiverXkbConfigV1.stop()` request and wait for a
        :func:`RiverXkbConfigV1.finished()` event. Once the finished event is
        received it is safe to destroy this object and any other objects
        created through this interface.
        """
        self._marshal(1)
        self._destroy()

    @RiverXkbConfigV1.request(
        Argument(ArgumentType.NewId, interface=RiverXkbKeymapV1),
        Argument(ArgumentType.FileDescriptor),
        Argument(ArgumentType.Uint),
    )
    def create_keymap(self, fd: int, format: int) -> Proxy[RiverXkbKeymapV1]:
        """Create a keymap object

        The server must be able to mmap the fd with MAP_PRIVATE. The server
        will fstat the fd to obtain the size of the keymap. The client must not
        modify the contents of the fd after making this request. The client
        should seal the fd with fcntl.

        :param fd:
        :type fd:
            `ArgumentType.FileDescriptor`
        :param format:
        :type format:
            `ArgumentType.Uint`
        :returns:
            :class:`~pywayland.protocol.river_xkb_config_v1.RiverXkbKeymapV1`
        """
        id = self._marshal_constructor(2, RiverXkbKeymapV1, fd, format)
        return id


class RiverXkbConfigV1Resource(Resource):
    interface = RiverXkbConfigV1

    @RiverXkbConfigV1.event()
    def finished(self) -> None:
        """The server has finished with the object

        This event indicates that the server will send no further events on
        this object. The client should destroy the object. See
        :func:`RiverXkbConfigV1.destroy()` for more information.
        """
        self._post_event(0)

    @RiverXkbConfigV1.event(
        Argument(ArgumentType.NewId, interface=RiverXkbKeyboardV1),
    )
    def xkb_keyboard(self, id: RiverXkbKeyboardV1) -> None:
        """New xkb keyboard

        A new xkbcommon keyboard has been created. Not every
        :class:`~pywayland.protocol.river_input_management_v1.RiverInputDeviceV1`
        is necessarily an xkbcommon keyboard as well.

        :param id:
        :type id:
            :class:`~pywayland.protocol.river_xkb_config_v1.RiverXkbKeyboardV1`
        """
        self._post_event(1, id)


class RiverXkbConfigV1Global(Global):
    interface = RiverXkbConfigV1


RiverXkbConfigV1._gen_c()
RiverXkbConfigV1.proxy_class = RiverXkbConfigV1Proxy
RiverXkbConfigV1.resource_class = RiverXkbConfigV1Resource
RiverXkbConfigV1.global_class = RiverXkbConfigV1Global
