# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2026 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from ..river_input_management_v1 import RiverInputDeviceV1
from .river_xkb_keymap_v1 import RiverXkbKeymapV1


class RiverXkbKeyboardV1(Interface):
    """Xkbcommon keyboard device

    This object represent a physical keyboard which has its configuration and
    state managed by xkbcommon.
    """

    name = "river_xkb_keyboard_v1"
    version = 1

    class error(enum.IntEnum):
        invalid_keymap = 0


class RiverXkbKeyboardV1Proxy(Proxy[RiverXkbKeyboardV1]):
    interface = RiverXkbKeyboardV1

    @RiverXkbKeyboardV1.request()
    def destroy(self) -> None:
        """Destroy the xkb keyboard object

        This request indicates that the client will no longer use the keyboard
        object and that it may be safely destroyed.
        """
        self._marshal(0)
        self._destroy()

    @RiverXkbKeyboardV1.request(
        Argument(ArgumentType.Object, interface=RiverXkbKeymapV1),
    )
    def set_keymap(self, keymap: RiverXkbKeymapV1) -> None:
        """Set the keymap

        Set the keymap for the keyboard.

        It is a protocol error to pass a keymap object for which the
        :func:`RiverXkbKeymapV1.success()
        <pywayland.protocol.river_xkb_config_v1.RiverXkbKeymapV1.success>`
        event was not received.

        :param keymap:
        :type keymap:
            :class:`~pywayland.protocol.river_xkb_config_v1.RiverXkbKeymapV1`
        """
        self._marshal(1, keymap)

    @RiverXkbKeyboardV1.request(
        Argument(ArgumentType.Int),
    )
    def set_layout_by_index(self, index: int) -> None:
        """Set the active layout by index

        Set the active layout for the keyboard's keymap. Has no effect if the
        layout index is out of bounds for the current keymap.

        :param index:
        :type index:
            `ArgumentType.Int`
        """
        self._marshal(2, index)

    @RiverXkbKeyboardV1.request(
        Argument(ArgumentType.String),
    )
    def set_layout_by_name(self, name: str) -> None:
        """Set the active layout by name

        Set the active layout for the keyboard's keymap. Has no effect if there
        is no layout with the give name for the keyboard's keymap.

        :param name:
        :type name:
            `ArgumentType.String`
        """
        self._marshal(3, name)

    @RiverXkbKeyboardV1.request()
    def capslock_enable(self) -> None:
        """Enable capslock

        Enable capslock for the keyboard.
        """
        self._marshal(4)

    @RiverXkbKeyboardV1.request()
    def capslock_disable(self) -> None:
        """Disable capslock

        Disable capslock for the keyboard.
        """
        self._marshal(5)

    @RiverXkbKeyboardV1.request()
    def numlock_enable(self) -> None:
        """Enable numlock

        Enable numlock for the keyboard.
        """
        self._marshal(6)

    @RiverXkbKeyboardV1.request()
    def numlock_disable(self) -> None:
        """Disable numlock

        Disable numlock for the keyboard.
        """
        self._marshal(7)


class RiverXkbKeyboardV1Resource(Resource):
    interface = RiverXkbKeyboardV1

    @RiverXkbKeyboardV1.event()
    def removed(self) -> None:
        """The xkb keyboard is removed

        This event indicates that the xkb keyboard has been removed.

        The server will send no further events on this object and ignore any
        request (other than :func:`RiverXkbKeyboardV1.destroy()`) made after
        this event is sent. The client should destroy this object with the
        :func:`RiverXkbKeyboardV1.destroy()` request to free up resources.
        """
        self._post_event(0)

    @RiverXkbKeyboardV1.event(
        Argument(ArgumentType.Object, interface=RiverInputDeviceV1),
    )
    def input_device(self, device: RiverInputDeviceV1) -> None:
        """Corresponding river input device

        The
        :class:`~pywayland.protocol.river_input_management_v1.RiverInputDeviceV1`
        corresponding to this xkb keyboard. This event will always be the first
        event sent on the :class:`RiverXkbKeyboardV1` object, and it will be
        sent exactly once.

        :param device:
        :type device:
            :class:`~pywayland.protocol.river_input_management_v1.RiverInputDeviceV1`
        """
        self._post_event(1, device)

    @RiverXkbKeyboardV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.String, nullable=True),
    )
    def layout(self, index: int, name: str | None) -> None:
        """Currently active layout

        The currently active layout index and name. The name arg may be null if
        the active layout does not have a name.

        This event is sent once when the :class:`RiverXkbKeyboardV1` is created
        and again whenever the layout changes.

        :param index:
        :type index:
            `ArgumentType.Uint`
        :param name:
        :type name:
            `ArgumentType.String` or `None`
        """
        self._post_event(2, index, name)

    @RiverXkbKeyboardV1.event()
    def capslock_enabled(self) -> None:
        """Capslock is currently enabled

        Capslock is currently enabled for the keyboard.

        This event is sent once when the :class:`RiverXkbKeyboardV1` is created
        and again whenever the capslock state changes.
        """
        self._post_event(3)

    @RiverXkbKeyboardV1.event()
    def capslock_disabled(self) -> None:
        """Capslock is currently disabled

        Capslock is currently disabled for the keyboard.

        This event is sent once when the :class:`RiverXkbKeyboardV1` is created
        and again whenever the capslock state changes.
        """
        self._post_event(4)

    @RiverXkbKeyboardV1.event()
    def numlock_enabled(self) -> None:
        """Numlock is currently enabled

        Numlock is currently enabled for the keyboard.

        This event is sent once when the :class:`RiverXkbKeyboardV1` is created
        and again whenever the numlock state changes.
        """
        self._post_event(5)

    @RiverXkbKeyboardV1.event()
    def numlock_disabled(self) -> None:
        """Numlock is currently disabled

        Numlock is currently disabled for the keyboard.

        This event is sent once when the :class:`RiverXkbKeyboardV1` is created
        and again whenever the numlock state changes.
        """
        self._post_event(6)


class RiverXkbKeyboardV1Global(Global):
    interface = RiverXkbKeyboardV1


RiverXkbKeyboardV1._gen_c()
RiverXkbKeyboardV1.proxy_class = RiverXkbKeyboardV1Proxy
RiverXkbKeyboardV1.resource_class = RiverXkbKeyboardV1Resource
RiverXkbKeyboardV1.global_class = RiverXkbKeyboardV1Global
