# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2026 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class RiverXkbKeymapV1(Interface):
    """Xkbcommon keymap

    This object is the result of attempting to create an xkbcommon keymap.
    """

    name = "river_xkb_keymap_v1"
    version = 1


class RiverXkbKeymapV1Proxy(Proxy[RiverXkbKeymapV1]):
    interface = RiverXkbKeymapV1

    @RiverXkbKeymapV1.request()
    def destroy(self) -> None:
        """Destroy the keymap object

        This request indicates that the client will no longer use the keymap
        object and that it may be safely destroyed.
        """
        self._marshal(0)
        self._destroy()


class RiverXkbKeymapV1Resource(Resource):
    interface = RiverXkbKeymapV1

    @RiverXkbKeymapV1.event()
    def success(self) -> None:
        """Keymap creation succeeded

        The keymap object was successfully created and may be used with the
        :func:`RiverXkbKeyboardV1.set_keymap()
        <pywayland.protocol.river_xkb_config_v1.RiverXkbKeyboardV1.set_keymap>`
        request.
        """
        self._post_event(0)

    @RiverXkbKeymapV1.event(
        Argument(ArgumentType.String),
    )
    def failure(self, error_msg: str) -> None:
        """Keymap creation failed

        The compositor failed to create a keymap from the given parameters.

        It is a protocol error to use this keymap object with
        :func:`RiverXkbKeyboardV1.set_keymap()
        <pywayland.protocol.river_xkb_config_v1.RiverXkbKeyboardV1.set_keymap>`.

        :param error_msg:
        :type error_msg:
            `ArgumentType.String`
        """
        self._post_event(1, error_msg)


class RiverXkbKeymapV1Global(Global):
    interface = RiverXkbKeymapV1


RiverXkbKeymapV1._gen_c()
RiverXkbKeymapV1.proxy_class = RiverXkbKeymapV1Proxy
RiverXkbKeymapV1.resource_class = RiverXkbKeymapV1Resource
RiverXkbKeymapV1.global_class = RiverXkbKeymapV1Global
