# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2025 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from ..wayland import WlOutput


class RiverInputDeviceV1(Interface):
    """An input device

    An input device represents a physical keyboard, mouse, touchscreen, or
    drawing tablet tool. It is assigned to exactly one seat at a time. By
    default, all input devices are assigned to the default seat.
    """

    name = "river_input_device_v1"
    version = 1

    class error(enum.IntEnum):
        invalid_repeat_info = 0
        invalid_scroll_factor = 1
        invalid_map_to_rectangle = 2

    class type(enum.IntEnum):
        keyboard = 0
        pointer = 1
        touch = 2
        tablet = 3


class RiverInputDeviceV1Proxy(Proxy[RiverInputDeviceV1]):
    interface = RiverInputDeviceV1

    @RiverInputDeviceV1.request()
    def destroy(self) -> None:
        """Destroy the input device object

        This request indicates that the client will no longer use the input
        device object and that it may be safely destroyed.
        """
        self._marshal(0)
        self._destroy()

    @RiverInputDeviceV1.request(
        Argument(ArgumentType.String),
    )
    def assign_to_seat(self, name: str) -> None:
        """Assign the input device to a seat

        Assign the input device to a seat. All input devices not explicitly
        assigned to a seat are considered assigned to the default seat.

        Has no effect if a seat with the given name does not exist.

        :param name:
            name of the seat
        :type name:
            `ArgumentType.String`
        """
        self._marshal(1, name)

    @RiverInputDeviceV1.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_repeat_info(self, rate: int, delay: int) -> None:
        """Set keyboard repeat rate and delay

        Set repeat rate and delay for a keyboard input device. Has no effect if
        the device is not a keyboard.

        Negative values for either rate or delay are illegal. A rate of zero
        will disable any repeating (regardless of the value of delay).

        :param rate:
            rate in key repeats per second
        :type rate:
            `ArgumentType.Int`
        :param delay:
            delay in milliseconds
        :type delay:
            `ArgumentType.Int`
        """
        self._marshal(2, rate, delay)

    @RiverInputDeviceV1.request(
        Argument(ArgumentType.Fixed),
    )
    def set_scroll_factor(self, factor: float) -> None:
        """Set scroll factor

        Set the scroll factor for a pointer input device. Has no effect if the
        device is not a pointer.

        For example, a factor of 0.5 will make scrolling twice as slow while a
        factor of 3.0 will make scrolling 3 times as fast.

        Setting a scroll factor less than 0 is a protocol error.

        :param factor:
        :type factor:
            `ArgumentType.Fixed`
        """
        self._marshal(3, factor)

    @RiverInputDeviceV1.request(
        Argument(ArgumentType.Object, interface=WlOutput, nullable=True),
    )
    def map_to_output(self, output: WlOutput | None) -> None:
        """Map input device to the given output

        Map the input device to the given output. Has no effect if the device
        is not a pointer, touch, or tablet device.

        If mapped to both an output and a rectangle, the rectangle has
        priority.

        Passing null clears an existing mapping.

        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput` or `None`
        """
        self._marshal(4, output)

    @RiverInputDeviceV1.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def map_to_rectangle(self, x: int, y: int, width: int, height: int) -> None:
        """Map input device to the given rectangle

        Map the input device to the given rectangle in the global compositor
        coordinate space. Has no effect if the device is not a pointer, touch,
        or tablet device.

        If mapped to both an output and a rectangle, the rectangle has
        priority.

        Width and height must be greater than or equal to 0.

        Passing 0 for width or height clears an existing mapping.

        :param x:
        :type x:
            `ArgumentType.Int`
        :param y:
        :type y:
            `ArgumentType.Int`
        :param width:
        :type width:
            `ArgumentType.Int`
        :param height:
        :type height:
            `ArgumentType.Int`
        """
        self._marshal(5, x, y, width, height)


class RiverInputDeviceV1Resource(Resource):
    interface = RiverInputDeviceV1

    @RiverInputDeviceV1.event()
    def removed(self) -> None:
        """The input device is removed

        This event indicates that the input device has been removed.

        The server will send no further events on this object and ignore any
        request (other than :func:`RiverInputDeviceV1.destroy()`) made after
        this event is sent. The client should destroy this object with the
        :func:`RiverInputDeviceV1.destroy()` request to free up resources.
        """
        self._post_event(0)

    @RiverInputDeviceV1.event(
        Argument(ArgumentType.Uint),
    )
    def type(self, type: int) -> None:
        """The type of the input device

        The type of the input device. This event is sent once when the
        :class:`RiverInputDeviceV1` object is created. The device type cannot
        change during the lifetime of the object.

        :param type:
        :type type:
            `ArgumentType.Uint`
        """
        self._post_event(1, type)

    @RiverInputDeviceV1.event(
        Argument(ArgumentType.String),
    )
    def name(self, name: str) -> None:
        """The name of the input device

        The name of the input device. This event is sent once when the
        :class:`RiverInputDeviceV1` object is created. The device name cannot
        change during the lifetime of the object.

        :param name:
        :type name:
            `ArgumentType.String`
        """
        self._post_event(2, name)


class RiverInputDeviceV1Global(Global):
    interface = RiverInputDeviceV1


RiverInputDeviceV1._gen_c()
RiverInputDeviceV1.proxy_class = RiverInputDeviceV1Proxy
RiverInputDeviceV1.resource_class = RiverInputDeviceV1Resource
RiverInputDeviceV1.global_class = RiverInputDeviceV1Global
