# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2025 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .river_input_device_v1 import RiverInputDeviceV1


class RiverInputManagerV1(Interface):
    """Input manager global interface

    Input manager global interface.
    """

    name = "river_input_manager_v1"
    version = 1

    class error(enum.IntEnum):
        invalid_destroy = 0


class RiverInputManagerV1Proxy(Proxy[RiverInputManagerV1]):
    interface = RiverInputManagerV1

    @RiverInputManagerV1.request()
    def stop(self) -> None:
        """Stop sending events

        This request indicates that the client no longer wishes to receive
        events on this object.

        The Wayland protocol is asynchronous, which means the server may send
        further events until the stop request is processed. The client must
        wait for a :func:`RiverInputManagerV1.finished()` event before
        destroying this object.
        """
        self._marshal(0)

    @RiverInputManagerV1.request()
    def destroy(self) -> None:
        """Destroy the :class:`RiverInputManagerV1` object

        This request should be called after the finished event has been
        received to complete destruction of the object.

        It is a protocol error to make this request before the finished event
        has been received.

        If a client wishes to destroy this object it should send a
        :func:`RiverInputManagerV1.stop()` request and wait for a
        :func:`RiverInputManagerV1.finished()` event. Once the finished event
        is received it is safe to destroy this object and any other objects
        created through this interface.
        """
        self._marshal(1)
        self._destroy()

    @RiverInputManagerV1.request(
        Argument(ArgumentType.String),
    )
    def create_seat(self, name: str) -> None:
        """Create a new seat

        Create a new seat with the given name. Has no effect if a seat with the
        given name already exists.

        The default seat with name "default" always exists and does not need to
        be explicitly created.

        :param name:
        :type name:
            `ArgumentType.String`
        """
        self._marshal(2, name)

    @RiverInputManagerV1.request(
        Argument(ArgumentType.String),
    )
    def destroy_seat(self, name: str) -> None:
        """Destroy a seat

        Destroy the seat with the given name. Has no effect if a seat with the
        given name does not exist.

        The default seat with name "default" cannot be destroyed and attempting
        to destroy it will have no effect.

        Any input devices assigned to the destroyed seat at the time of
        destruction are assigned to the default seat.

        :param name:
        :type name:
            `ArgumentType.String`
        """
        self._marshal(3, name)


class RiverInputManagerV1Resource(Resource):
    interface = RiverInputManagerV1

    @RiverInputManagerV1.event()
    def finished(self) -> None:
        """The server has finished with the input manager

        This event indicates that the server will send no further events on
        this object. The client should destroy the object. See
        :func:`RiverInputManagerV1.destroy()` for more information.
        """
        self._post_event(0)

    @RiverInputManagerV1.event(
        Argument(ArgumentType.NewId, interface=RiverInputDeviceV1),
    )
    def input_device(self, id: RiverInputDeviceV1) -> None:
        """New input device

        A new input device has been created.

        :param id:
        :type id:
            :class:`~pywayland.protocol.river_input_management_v1.RiverInputDeviceV1`
        """
        self._post_event(1, id)


class RiverInputManagerV1Global(Global):
    interface = RiverInputManagerV1


RiverInputManagerV1._gen_c()
RiverInputManagerV1.proxy_class = RiverInputManagerV1Proxy
RiverInputManagerV1.resource_class = RiverInputManagerV1Resource
RiverInputManagerV1.global_class = RiverInputManagerV1Global
