# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2024 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from .river_decoration_v1 import RiverDecorationV1  # noqa: F401
from .river_node_v1 import RiverNodeV1  # noqa: F401
from .river_output_v1 import RiverOutputV1  # noqa: F401
from .river_pointer_binding_v1 import RiverPointerBindingV1  # noqa: F401
from .river_seat_v1 import RiverSeatV1  # noqa: F401
from .river_shell_surface_v1 import RiverShellSurfaceV1  # noqa: F401
from .river_window_manager_v1 import RiverWindowManagerV1  # noqa: F401
from .river_window_v1 import RiverWindowV1  # noqa: F401

# Patch lazy interface references now that all modules are loaded.
# RiverWindowV1 events pointer_move_requested and pointer_resize_requested
# have Object arguments with interface=None due to circular imports.
for _event in RiverWindowV1.events:
    if _event.name in ("pointer_move_requested", "pointer_resize_requested"):
        for _arg in _event.arguments:
            if _arg.interface is None and _arg.argument_type.name == "Object":
                object.__setattr__(_arg, 'interface', RiverSeatV1)
