# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2024 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .river_node_v1 import RiverNodeV1


class RiverShellSurfaceV1(Interface):
    """A surface for window manager ui

    The window manager might use a shell surface to display a status bar,
    background image, desktop notifications, launcher, desktop menu, or
    whatever else it wants.
    """

    name = "river_shell_surface_v1"
    version = 3

    class error(enum.IntEnum):
        node_exists = 0
        no_commit = 1


class RiverShellSurfaceV1Proxy(Proxy[RiverShellSurfaceV1]):
    interface = RiverShellSurfaceV1

    @RiverShellSurfaceV1.request()
    def destroy(self) -> None:
        """Destroy the shell surface object

        This request indicates that the client will no longer use the shell
        surface object and that it may be safely destroyed.
        """
        self._marshal(0)
        self._destroy()

    @RiverShellSurfaceV1.request(
        Argument(ArgumentType.NewId, interface=RiverNodeV1),
    )
    def get_node(self) -> Proxy[RiverNodeV1]:
        """Get the shell surface's render list node

        Get the node in the render list corresponding to the shell surface.

        It is a protocol error to make this request more than once for a single
        shell surface.

        :returns:
            :class:`~pywayland.protocol.river_window_management_v1.RiverNodeV1`
        """
        id = self._marshal_constructor(1, RiverNodeV1)
        return id

    @RiverShellSurfaceV1.request()
    def sync_next_commit(self) -> None:
        """Sync next surface commit to window manager commit

        Synchronize application of the next :func:`WlSurface.commit()
        <pywayland.protocol.wayland.WlSurface.commit>` request on the shell
        surface with rest of the rendering state atomically applied with the
        next :func:`RiverWindowManagerV1.render_finish()
        <pywayland.protocol.river_window_management_v1.RiverWindowManagerV1.render_finish>`
        request.

        The client must make a :func:`WlSurface.commit()
        <pywayland.protocol.wayland.WlSurface.commit>` request on the shell
        surface after this request and before the render_finish request,
        failure to do so is a protocol error.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.
        """
        self._marshal(2)


class RiverShellSurfaceV1Resource(Resource):
    interface = RiverShellSurfaceV1


class RiverShellSurfaceV1Global(Global):
    interface = RiverShellSurfaceV1


RiverShellSurfaceV1._gen_c()
RiverShellSurfaceV1.proxy_class = RiverShellSurfaceV1Proxy
RiverShellSurfaceV1.resource_class = RiverShellSurfaceV1Resource
RiverShellSurfaceV1.global_class = RiverShellSurfaceV1Global
