# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2024 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class RiverNodeV1(Interface):
    """A node in the render list

    The render list is a list of nodes that determines the rendering order of
    the compositor. Nodes may correspond to windows or shell surfaces. The
    relative ordering of nodes may be changed with the place_above and
    place_below requests, changing the rendering order.

    The initial position of a node in the render list is undefined, the window
    manager client must use the place_above or place_below request to guarantee
    a specific rendering order.
    """

    name = "river_node_v1"
    version = 3


class RiverNodeV1Proxy(Proxy[RiverNodeV1]):
    interface = RiverNodeV1

    @RiverNodeV1.request()
    def destroy(self) -> None:
        """Destroy the decoration object

        This request indicates that the client will no longer use the node
        object and that it may be safely destroyed.
        """
        self._marshal(0)
        self._destroy()

    @RiverNodeV1.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_position(self, x: int, y: int) -> None:
        """Set absolute position of the node

        Set the absolute position of the node in the compositor's logical
        coordinate space. The x and y coordinates may be positive or negative.

        Note that the position of a
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowV1`
        refers to the position of the window content and is unaffected by the
        presence of borders or decoration surfaces.

        If this request is never sent, the position of the node is undefined by
        this protocol and left up to the compositor.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.

        :param x:
        :type x:
            `ArgumentType.Int`
        :param y:
        :type y:
            `ArgumentType.Int`
        """
        self._marshal(1, x, y)

    @RiverNodeV1.request()
    def place_top(self) -> None:
        """Place node above all other nodes

        This request places the node above all other nodes in the compositor's
        render list.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.
        """
        self._marshal(2)

    @RiverNodeV1.request()
    def place_bottom(self) -> None:
        """Place node below all other nodes

        This request places the node below all other nodes in the compositor's
        render list.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.
        """
        self._marshal(3)

    @RiverNodeV1.request(
        Argument(ArgumentType.Object, interface=RiverNodeV1),
    )
    def place_above(self, other: RiverNodeV1) -> None:
        """Place node above another node

        This request places the node directly above another node in the
        compositor's render list.

        Attempting to place a node above itself has no effect.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.

        :param other:
        :type other:
            :class:`RiverNodeV1`
        """
        self._marshal(4, other)

    @RiverNodeV1.request(
        Argument(ArgumentType.Object, interface=RiverNodeV1),
    )
    def place_below(self, other: RiverNodeV1) -> None:
        """Place node below another node

        This request places the node directly below another node in the
        compositor's render list.

        Attempting to place a node below itself has no effect.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.

        :param other:
        :type other:
            :class:`RiverNodeV1`
        """
        self._marshal(5, other)


class RiverNodeV1Resource(Resource):
    interface = RiverNodeV1


class RiverNodeV1Global(Global):
    interface = RiverNodeV1


RiverNodeV1._gen_c()
RiverNodeV1.proxy_class = RiverNodeV1Proxy
RiverNodeV1.resource_class = RiverNodeV1Resource
RiverNodeV1.global_class = RiverNodeV1Global
