# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2024 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class RiverDecorationV1(Interface):
    """A window decoration

    The rendering order of windows with decorations is follows:

    1. Decorations created with get_decoration_below at the bottom 2. Window
    content 3. Borders configured with :func:`RiverWindowV1.set_borders()
    <pywayland.protocol.river_window_management_v1.RiverWindowV1.set_borders>`
    4. Decorations created with get_decoration_above at the top

    The relative ordering of decoration surfaces above/below a window is
    undefined by this protocol and left up to the compositor.
    """

    name = "river_decoration_v1"
    version = 3

    class error(enum.IntEnum):
        no_commit = 0


class RiverDecorationV1Proxy(Proxy[RiverDecorationV1]):
    interface = RiverDecorationV1

    @RiverDecorationV1.request()
    def destroy(self) -> None:
        """Destroy the decoration object

        This request indicates that the client will no longer use the
        decoration object and that it may be safely destroyed.
        """
        self._marshal(0)
        self._destroy()

    @RiverDecorationV1.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_offset(self, x: int, y: int) -> None:
        """Set offset from the window's top left corner

        This request sets the offset of the decoration surface from the top
        left corner of the window.

        If this request is never sent, the x and y offsets are undefined by
        this protocol and left up to the compositor.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.

        :param x:
        :type x:
            `ArgumentType.Int`
        :param y:
        :type y:
            `ArgumentType.Int`
        """
        self._marshal(1, x, y)

    @RiverDecorationV1.request()
    def sync_next_commit(self) -> None:
        """Sync next commit with other rendering state

        Synchronize application of the next :func:`WlSurface.commit()
        <pywayland.protocol.wayland.WlSurface.commit>` request on the
        decoration surface with rest of the state atomically applied with the
        next :func:`RiverWindowManagerV1.render_finish()
        <pywayland.protocol.river_window_management_v1.RiverWindowManagerV1.render_finish>`
        request.

        The client must make a :func:`WlSurface.commit()
        <pywayland.protocol.wayland.WlSurface.commit>` request on the
        decoration surface after this request and before the render_finish
        request, failure to do so is a protocol error.

        This request modifies rendering state and may only be made as part of a
        render sequence, see the
        :class:`~pywayland.protocol.river_window_management_v1.RiverWindowManagerV1`
        description.
        """
        self._marshal(2)


class RiverDecorationV1Resource(Resource):
    interface = RiverDecorationV1


class RiverDecorationV1Global(Global):
    interface = RiverDecorationV1


RiverDecorationV1._gen_c()
RiverDecorationV1.proxy_class = RiverDecorationV1Proxy
RiverDecorationV1.resource_class = RiverDecorationV1Resource
RiverDecorationV1.global_class = RiverDecorationV1Global
