# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: © 2024 Isaac Freund
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class RiverOutputV1(Interface):
    """A logical output

    An area in the compositor's logical coordinate space that should be treated
    as a single output for window management purposes. This area may correspond
    to a single physical output or multiple physical outputs in the case of
    mirroring or tiled monitors depending on the hardware and compositor
    configuration.
    """

    name = "river_output_v1"
    version = 3


class RiverOutputV1Proxy(Proxy[RiverOutputV1]):
    interface = RiverOutputV1

    @RiverOutputV1.request()
    def destroy(self) -> None:
        """Destroy the output object

        This request indicates that the client will no longer use the output
        object and that it may be safely destroyed.

        This request should be made after the :func:`RiverOutputV1.removed()`
        event is received to complete destruction of the output.
        """
        self._marshal(0)
        self._destroy()


class RiverOutputV1Resource(Resource):
    interface = RiverOutputV1

    @RiverOutputV1.event()
    def removed(self) -> None:
        """The output is removed

        This event indicates that the logical output is no longer conceptually
        part of window management space.

        The server will send no further events on this object and ignore any
        request (other than :func:`RiverOutputV1.destroy()`) made after this
        event is sent. The client should destroy this object with the
        :func:`RiverOutputV1.destroy()` request to free up resources.

        This event may be sent because a corresponding physical output has been
        physically unplugged or because some output configuration has changed.

        This event will be followed by a manage_start event after all other new
        state has been sent by the server.
        """
        self._post_event(0)

    @RiverOutputV1.event(
        Argument(ArgumentType.Uint),
    )
    def wl_output(self, name: int) -> None:
        """Corresponding :class:`~pywayland.protocol.wayland.WlOutput`

        The :class:`~pywayland.protocol.wayland.WlOutput` object corresponding
        to the :class:`RiverOutputV1`. The argument is the global name of the
        :class:`~pywayland.protocol.wayland.WlOutput` advertised with
        :func:`WlRegistry.global()
        <pywayland.protocol.wayland.WlRegistry.global>`.

        It is guaranteed that the corresponding
        :class:`~pywayland.protocol.wayland.WlOutput` is advertised before this
        event is sent.

        This event is sent exactly once. The
        :class:`~pywayland.protocol.wayland.WlOutput` associated with a
        :class:`RiverOutputV1` cannot change. It is guaranteed that there is a
        1-to-1 mapping between :class:`~pywayland.protocol.wayland.WlOutput`
        and :class:`RiverOutputV1` objects.

        The global_remove event for the corresponding
        :class:`~pywayland.protocol.wayland.WlOutput` may be sent before the
        :func:`RiverOutputV1.remove()` event. This is due to the fact that
        :class:`RiverOutputV1` state changes are synced to the river window
        management manage sequence while changes to globals are not.

        Rationale: The window manager may need information provided by the
        :class:`~pywayland.protocol.wayland.WlOutput` interface such as the
        name/description. It also may need the
        :class:`~pywayland.protocol.wayland.WlOutput` object to start
        screencopy for example.

        :param name:
            name of the :class:`~pywayland.protocol.wayland.WlOutput` global
        :type name:
            `ArgumentType.Uint`
        """
        self._post_event(1, name)

    @RiverOutputV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def position(self, x: int, y: int) -> None:
        """Output position

        This event indicates the position of the output in the compositor's
        logical coordinate space. The x and y coordinates may be positive or
        negative.

        This event is sent once when the :class:`RiverOutputV1` is created and
        again whenever the position changes.

        This event will be followed by a manage_start event after all other new
        state has been sent by the server.

        The server must guarantee that the position and dimensions events do
        not cause the areas of multiple logical outputs to overlap when the
        corresponding manage_start event is received.

        :param x:
        :type x:
            `ArgumentType.Int`
        :param y:
        :type y:
            `ArgumentType.Int`
        """
        self._post_event(2, x, y)

    @RiverOutputV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def dimensions(self, width: int, height: int) -> None:
        """Output dimensions

        This event indicates the dimensions of the output in the compositor's
        logical coordinate space. The width and height will always be strictly
        greater than zero.

        This event is sent once when the :class:`RiverOutputV1` is created and
        again whenever the dimensions change.

        This event will be followed by a manage_start event after all other new
        state has been sent by the server.

        The server must guarantee that the position and dimensions events do
        not cause the areas of multiple logical outputs to overlap when the
        corresponding manage_start event is received.

        :param width:
        :type width:
            `ArgumentType.Int`
        :param height:
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(3, width, height)


class RiverOutputV1Global(Global):
    interface = RiverOutputV1


RiverOutputV1._gen_c()
RiverOutputV1.proxy_class = RiverOutputV1Proxy
RiverOutputV1.resource_class = RiverOutputV1Resource
RiverOutputV1.global_class = RiverOutputV1Global
